name: CI

on:
  pull_request:
    types: [closed] 

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Pull request merged
      if: github.event.pull_request.merged == true
      run: echo merged
      
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        git diff-tree --no-commit-id --name-only -r ${{ github.sha }}
